language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-blink-baremetal
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-cellular
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-ethernet-tls
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-synchronization


install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - platformio platform install file://.

script:
  - platformio run -s -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
