language: python
python:
  - "3.9"
os:
  - linux
git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-blink-baremetal
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-cellular
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-ethernet-tls
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-synchronization


install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - pio platform install file://.

script:
  - pio run -s -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
