build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-blink-baremetal"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-cellular"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos-ethernet-tls"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/zephyr-synchronization"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python37\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: platformio platform install file://.

test_script:
  - cmd: platformio run -s -d %PLATFORMIO_PROJECT_DIR%

